/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityDuration {
    #[serde(rename = "activity_type", skip_serializing_if = "Option::is_none")]
    pub activity_type: Option<String>,
    #[serde(rename = "seconds", skip_serializing_if = "Option::is_none")]
    pub seconds: Option<f64>,
}

impl ActivityDuration {
    pub fn new() -> ActivityDuration {
        ActivityDuration {
            activity_type: None,
            seconds: None,
        }
    }
}

