/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientErrorResponseContent {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<serde_json::Value>>,
}

impl ClientErrorResponseContent {
    pub fn new(r#type: String) -> ClientErrorResponseContent {
        ClientErrorResponseContent {
            r#type,
            errors: None,
        }
    }
}

