/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfluenceDetail {
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "atlassian_email")]
    pub atlassian_email: String,
}

impl ConfluenceDetail {
    pub fn new(domain: String, atlassian_email: String) -> ConfluenceDetail {
        ConfluenceDetail {
            domain,
            atlassian_email,
        }
    }
}

