/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionDetail {
    #[serde(rename = "connection_id")]
    pub connection_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "created_by")]
    pub created_by: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl ConnectionDetail {
    pub fn new(connection_id: String, name: String, r#type: String, created_by: String, created_at: String, updated_at: String) -> ConnectionDetail {
        ConnectionDetail {
            connection_id,
            name,
            r#type,
            created_by,
            created_at,
            updated_at,
        }
    }
}

