/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateKnowledgeBaseRequestContent {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "data_connector_ids")]
    pub data_connector_ids: Vec<String>,
}

impl CreateKnowledgeBaseRequestContent {
    pub fn new(name: String, data_connector_ids: Vec<String>) -> CreateKnowledgeBaseRequestContent {
        CreateKnowledgeBaseRequestContent {
            name,
            description: None,
            data_connector_ids,
        }
    }
}

