/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateConnectionRequestContent {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "credentials")]
    pub credentials: Box<models::ConnectionCredentialsInput>,
}

impl CreateConnectionRequestContent {
    pub fn new(r#type: String, credentials: models::ConnectionCredentialsInput) -> CreateConnectionRequestContent {
        CreateConnectionRequestContent {
            r#type,
            name: None,
            credentials: Box::new(credentials),
        }
    }
}

