/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCheckoutSessionRequestContent {
    #[serde(rename = "price_lookup_key")]
    pub price_lookup_key: String,
}

impl CreateCheckoutSessionRequestContent {
    pub fn new(price_lookup_key: String) -> CreateCheckoutSessionRequestContent {
        CreateCheckoutSessionRequestContent {
            price_lookup_key,
        }
    }
}

