/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDeploymentRequestContent {
    #[serde(rename = "code_source", skip_serializing_if = "Option::is_none")]
    pub code_source: Option<Box<models::CodeSourceInput>>,
    #[serde(rename = "force", skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
}

impl CreateDeploymentRequestContent {
    pub fn new() -> CreateDeploymentRequestContent {
        CreateDeploymentRequestContent {
            code_source: None,
            force: None,
        }
    }
}

