/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateStructureRunRequestContent {
    #[serde(rename = "args")]
    pub args: Vec<String>,
    #[serde(rename = "env_vars", skip_serializing_if = "Option::is_none")]
    pub env_vars: Option<Vec<models::EnvVar>>,
}

impl CreateStructureRunRequestContent {
    pub fn new(args: Vec<String>) -> CreateStructureRunRequestContent {
        CreateStructureRunRequestContent {
            args,
            env_vars: None,
        }
    }
}

