/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCheckoutSessionResponseContent {
    #[serde(rename = "redirect_url")]
    pub redirect_url: String,
}

impl CreateCheckoutSessionResponseContent {
    pub fn new(redirect_url: String) -> CreateCheckoutSessionResponseContent {
        CreateCheckoutSessionResponseContent {
            redirect_url,
        }
    }
}

