/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateMessageResponseContent {
    #[serde(rename = "message_id")]
    pub message_id: String,
    #[serde(rename = "thread_id")]
    pub thread_id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "created_by")]
    pub created_by: String,
    #[serde(rename = "index")]
    pub index: f64,
    #[serde(rename = "input")]
    pub input: String,
    #[serde(rename = "output")]
    pub output: String,
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, serde_json::Value>,
}

impl CreateMessageResponseContent {
    pub fn new(message_id: String, thread_id: String, created_at: String, updated_at: String, created_by: String, index: f64, input: String, output: String, metadata: std::collections::HashMap<String, serde_json::Value>) -> CreateMessageResponseContent {
        CreateMessageResponseContent {
            message_id,
            thread_id,
            created_at,
            updated_at,
            created_by,
            index,
            input,
            output,
            metadata,
        }
    }
}

