/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBillingManagementUrlResponseContent {
    #[serde(rename = "billing_management_url")]
    pub billing_management_url: String,
}

impl CreateBillingManagementUrlResponseContent {
    pub fn new(billing_management_url: String) -> CreateBillingManagementUrlResponseContent {
        CreateBillingManagementUrlResponseContent {
            billing_management_url,
        }
    }
}

