/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataConnectorDetail {
    #[serde(rename = "data_connector_id")]
    pub data_connector_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "config")]
    pub config: Box<models::DataConnectorConfigUnion>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "created_by")]
    pub created_by: String,
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    #[serde(rename = "schedule_expression", skip_serializing_if = "Option::is_none")]
    pub schedule_expression: Option<String>,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "transforms", skip_serializing_if = "Option::is_none")]
    pub transforms: Option<Vec<models::TransformDetail>>,
}

impl DataConnectorDetail {
    pub fn new(data_connector_id: String, name: String, config: models::DataConnectorConfigUnion, created_at: String, updated_at: String, created_by: String, organization_id: String, r#type: String) -> DataConnectorDetail {
        DataConnectorDetail {
            data_connector_id,
            name,
            config: Box::new(config),
            description: None,
            created_at,
            updated_at,
            created_by,
            organization_id,
            schedule_expression: None,
            r#type,
            transforms: None,
        }
    }
}

