/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DataConnectorConfigUnion {
    Confluence1(Box<models::Confluence1>),
    GoogleDrive1(Box<models::GoogleDrive1>),
    TempGoogleDrive1(Box<models::TempGoogleDrive1>),
    Webscraper1(Box<models::Webscraper1>),
    Structure1(Box<models::Structure1>),
    S31(Box<models::S31>),
}

impl Default for DataConnectorConfigUnion {
    fn default() -> Self {
        Self::Confluence1(Default::default())
    }
}

