/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DataConnectorConfigInputUnion {
    Confluence(Box<models::Confluence>),
    GoogleDrive(Box<models::GoogleDrive>),
    TempGoogleDrive(Box<models::TempGoogleDrive>),
    Webscraper(Box<models::Webscraper>),
    Structure(Box<models::Structure>),
    S3(Box<models::S3>),
}

impl Default for DataConnectorConfigInputUnion {
    fn default() -> Self {
        Self::Confluence(Default::default())
    }
}

