/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DurationTimeseriesElement {
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    #[serde(rename = "seconds_p100", skip_serializing_if = "Option::is_none")]
    pub seconds_p100: Option<f64>,
    #[serde(rename = "seconds_p50", skip_serializing_if = "Option::is_none")]
    pub seconds_p50: Option<f64>,
    #[serde(rename = "seconds_p0", skip_serializing_if = "Option::is_none")]
    pub seconds_p0: Option<f64>,
}

impl DurationTimeseriesElement {
    pub fn new() -> DurationTimeseriesElement {
        DurationTimeseriesElement {
            time: None,
            seconds_p100: None,
            seconds_p50: None,
            seconds_p0: None,
        }
    }
}

