/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EmbeddingModel {
    #[serde(rename = "text-embedding-ada-002")]
    Ada002,
    #[serde(rename = "text-embedding-3-small")]
    Variant3Small,

}

impl std::fmt::Display for EmbeddingModel {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ada002 => write!(f, "text-embedding-ada-002"),
            Self::Variant3Small => write!(f, "text-embedding-3-small"),
        }
    }
}

impl Default for EmbeddingModel {
    fn default() -> EmbeddingModel {
        Self::Ada002
    }
}

