/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Entitlement {
    #[serde(rename = "FREE")]
    Free,
    #[serde(rename = "PAID")]
    Paid,
    #[serde(rename = "UNPAID")]
    Unpaid,
    #[serde(rename = "EXPIRED")]
    Expired,

}

impl std::fmt::Display for Entitlement {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Free => write!(f, "FREE"),
            Self::Paid => write!(f, "PAID"),
            Self::Unpaid => write!(f, "UNPAID"),
            Self::Expired => write!(f, "EXPIRED"),
        }
    }
}

impl Default for Entitlement {
    fn default() -> Entitlement {
        Self::Free
    }
}

