/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnvVar {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<models::EnvVarSource>,
    #[serde(rename = "value")]
    pub value: String,
}

impl EnvVar {
    pub fn new(name: String, value: String) -> EnvVar {
        EnvVar {
            name,
            source: None,
            value,
        }
    }
}

