/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EnvVarSource {
    #[serde(rename = "SECRET_REF")]
    SecretRef,
    #[serde(rename = "MANUAL")]
    Manual,

}

impl std::fmt::Display for EnvVarSource {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SecretRef => write!(f, "SECRET_REF"),
            Self::Manual => write!(f, "MANUAL"),
        }
    }
}

impl Default for EnvVarSource {
    fn default() -> EnvVarSource {
        Self::SecretRef
    }
}

