/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventInput {
    #[serde(rename = "payload", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payload: Option<Option<serde_json::Value>>,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "timestamp")]
    pub timestamp: f64,
}

impl EventInput {
    pub fn new(r#type: String, timestamp: f64) -> EventInput {
        EventInput {
            payload: None,
            r#type,
            timestamp,
        }
    }
}

