/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStructuresDashboardResponseContent {
    #[serde(rename = "run_count_gauge", skip_serializing_if = "Option::is_none")]
    pub run_count_gauge: Option<Box<models::RunCountGauge>>,
    #[serde(rename = "run_duration_gauge", skip_serializing_if = "Option::is_none")]
    pub run_duration_gauge: Option<Box<models::RunDurationGauge>>,
    #[serde(rename = "token_count_gauge", skip_serializing_if = "Option::is_none")]
    pub token_count_gauge: Option<Box<models::TokenCountGauge>>,
    #[serde(rename = "error_rate_gauge", skip_serializing_if = "Option::is_none")]
    pub error_rate_gauge: Option<Box<models::ErrorRateGauge>>,
    #[serde(rename = "duration_plot", skip_serializing_if = "Option::is_none")]
    pub duration_plot: Option<Box<models::DurationPlot>>,
    #[serde(rename = "deployment_count_gauge", skip_serializing_if = "Option::is_none")]
    pub deployment_count_gauge: Option<Box<models::DeploymentCountGauge>>,
    #[serde(rename = "deployment_duration_gauge", skip_serializing_if = "Option::is_none")]
    pub deployment_duration_gauge: Option<Box<models::DeploymentDurationGauge>>,
    #[serde(rename = "deployment_error_rate_gauge", skip_serializing_if = "Option::is_none")]
    pub deployment_error_rate_gauge: Option<Box<models::DeploymentErrorRateGauge>>,
}

impl GetStructuresDashboardResponseContent {
    pub fn new() -> GetStructuresDashboardResponseContent {
        GetStructuresDashboardResponseContent {
            run_count_gauge: None,
            run_duration_gauge: None,
            token_count_gauge: None,
            error_rate_gauge: None,
            duration_plot: None,
            deployment_count_gauge: None,
            deployment_duration_gauge: None,
            deployment_error_rate_gauge: None,
        }
    }
}

