/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStructureResponseContent {
    #[serde(rename = "structure_id")]
    pub structure_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "code")]
    pub code: Box<models::StructureCode>,
    #[serde(rename = "structure_config_file", skip_serializing_if = "Option::is_none")]
    pub structure_config_file: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    #[serde(rename = "created_by")]
    pub created_by: String,
    #[serde(rename = "env_vars")]
    pub env_vars: Vec<models::EnvVar>,
    #[serde(rename = "latest_deployment_id")]
    pub latest_deployment_id: String,
    #[serde(rename = "webhook_enabled")]
    pub webhook_enabled: bool,
}

impl GetStructureResponseContent {
    pub fn new(structure_id: String, name: String, description: String, code: models::StructureCode, created_at: String, updated_at: String, organization_id: String, created_by: String, env_vars: Vec<models::EnvVar>, latest_deployment_id: String, webhook_enabled: bool) -> GetStructureResponseContent {
        GetStructureResponseContent {
            structure_id,
            name,
            description,
            code: Box::new(code),
            structure_config_file: None,
            created_at,
            updated_at,
            organization_id,
            created_by,
            env_vars,
            latest_deployment_id,
            webhook_enabled,
        }
    }
}

