/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetKnowledgeBaseResponseContent {
    #[serde(rename = "knowledge_base_id")]
    pub knowledge_base_id: String,
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "created_by")]
    pub created_by: String,
    #[serde(rename = "data_connector_ids")]
    pub data_connector_ids: Vec<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl GetKnowledgeBaseResponseContent {
    pub fn new(knowledge_base_id: String, organization_id: String, name: String, created_at: String, updated_at: String, created_by: String, data_connector_ids: Vec<String>) -> GetKnowledgeBaseResponseContent {
        GetKnowledgeBaseResponseContent {
            knowledge_base_id,
            organization_id,
            name,
            created_at,
            updated_at,
            created_by,
            data_connector_ids,
            description: None,
        }
    }
}

