/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitHubCredentialsInput {
    #[serde(rename = "auth_code")]
    pub auth_code: String,
}

impl GitHubCredentialsInput {
    pub fn new(auth_code: String) -> GitHubCredentialsInput {
        GitHubCredentialsInput {
            auth_code,
        }
    }
}

