/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubStructureCodePushConfig {
    #[serde(rename = "branch")]
    pub branch: String,
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
}

impl GithubStructureCodePushConfig {
    pub fn new(branch: String) -> GithubStructureCodePushConfig {
        GithubStructureCodePushConfig {
            branch,
            tag: None,
        }
    }
}

