/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GoogleDriveInput {
    #[serde(rename = "auth_code")]
    pub auth_code: String,
    #[serde(rename = "file_ids")]
    pub file_ids: Vec<String>,
}

impl GoogleDriveInput {
    pub fn new(auth_code: String, file_ids: Vec<String>) -> GoogleDriveInput {
        GoogleDriveInput {
            auth_code,
            file_ids,
        }
    }
}

