/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAssistantRunsResponseContent {
    #[serde(rename = "assistant_runs")]
    pub assistant_runs: Vec<models::AssistantRunDetail>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::Pagination>,
}

impl ListAssistantRunsResponseContent {
    pub fn new(assistant_runs: Vec<models::AssistantRunDetail>, pagination: models::Pagination) -> ListAssistantRunsResponseContent {
        ListAssistantRunsResponseContent {
            assistant_runs,
            pagination: Box::new(pagination),
        }
    }
}

