/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListDataJobsResponseContent {
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<f64>,
    #[serde(rename = "data_jobs")]
    pub data_jobs: Vec<models::DataJobDetail>,
}

impl ListDataJobsResponseContent {
    pub fn new(data_jobs: Vec<models::DataJobDetail>) -> ListDataJobsResponseContent {
        ListDataJobsResponseContent {
            page: None,
            data_jobs,
        }
    }
}

