/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListKnowledgeBaseSearchesResponseContent {
    #[serde(rename = "knowledge_base_searches", skip_serializing_if = "Option::is_none")]
    pub knowledge_base_searches: Option<Vec<models::KnowledgeBaseSearchDetail>>,
}

impl ListKnowledgeBaseSearchesResponseContent {
    pub fn new() -> ListKnowledgeBaseSearchesResponseContent {
        ListKnowledgeBaseSearchesResponseContent {
            knowledge_base_searches: None,
        }
    }
}

