/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListDataConnectorsResponseContent {
    #[serde(rename = "data_connectors", skip_serializing_if = "Option::is_none")]
    pub data_connectors: Option<Vec<models::DataConnectorDetail>>,
}

impl ListDataConnectorsResponseContent {
    pub fn new() -> ListDataConnectorsResponseContent {
        ListDataConnectorsResponseContent {
            data_connectors: None,
        }
    }
}

