/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListThreadsResponseContent {
    #[serde(rename = "threads")]
    pub threads: Vec<models::ThreadDetail>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::Pagination>,
}

impl ListThreadsResponseContent {
    pub fn new(threads: Vec<models::ThreadDetail>, pagination: models::Pagination) -> ListThreadsResponseContent {
        ListThreadsResponseContent {
            threads,
            pagination: Box::new(pagination),
        }
    }
}

