/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListIntegrationsResponseContent {
    #[serde(rename = "integrations")]
    pub integrations: Vec<models::IntegrationDetail>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::Pagination>,
}

impl ListIntegrationsResponseContent {
    pub fn new(integrations: Vec<models::IntegrationDetail>, pagination: models::Pagination) -> ListIntegrationsResponseContent {
        ListIntegrationsResponseContent {
            integrations,
            pagination: Box::new(pagination),
        }
    }
}

