/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAssistantsResponseContent {
    #[serde(rename = "assistants")]
    pub assistants: Vec<models::AssistantDetail>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::Pagination>,
}

impl ListAssistantsResponseContent {
    pub fn new(assistants: Vec<models::AssistantDetail>, pagination: models::Pagination) -> ListAssistantsResponseContent {
        ListAssistantsResponseContent {
            assistants,
            pagination: Box::new(pagination),
        }
    }
}

