/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListMessagesResponseContent {
    #[serde(rename = "messages")]
    pub messages: Vec<models::MessageDetail>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::Pagination>,
}

impl ListMessagesResponseContent {
    pub fn new(messages: Vec<models::MessageDetail>, pagination: models::Pagination) -> ListMessagesResponseContent {
        ListMessagesResponseContent {
            messages,
            pagination: Box::new(pagination),
        }
    }
}

