/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListStructureRunsResponseContent {
    #[serde(rename = "structure_runs")]
    pub structure_runs: Vec<models::StructureRunDetail>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::Pagination>,
}

impl ListStructureRunsResponseContent {
    pub fn new(structure_runs: Vec<models::StructureRunDetail>, pagination: models::Pagination) -> ListStructureRunsResponseContent {
        ListStructureRunsResponseContent {
            structure_runs,
            pagination: Box::new(pagination),
        }
    }
}

