/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAssetsResponseContent {
    #[serde(rename = "assets")]
    pub assets: Vec<models::AssetDetail>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::Pagination>,
    #[serde(rename = "prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
    #[serde(rename = "postfix", skip_serializing_if = "Option::is_none")]
    pub postfix: Option<String>,
}

impl ListAssetsResponseContent {
    pub fn new(assets: Vec<models::AssetDetail>, pagination: models::Pagination) -> ListAssetsResponseContent {
        ListAssetsResponseContent {
            assets,
            pagination: Box::new(pagination),
            prefix: None,
            postfix: None,
        }
    }
}

