/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListDeploymentsResponseContent {
    #[serde(rename = "deployments")]
    pub deployments: Vec<models::DeploymentDetail>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::Pagination>,
}

impl ListDeploymentsResponseContent {
    pub fn new(deployments: Vec<models::DeploymentDetail>, pagination: models::Pagination) -> ListDeploymentsResponseContent {
        ListDeploymentsResponseContent {
            deployments,
            pagination: Box::new(pagination),
        }
    }
}

