/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListKnowledgeBaseQueriesResponseContent {
    #[serde(rename = "knowledge_base_queries", skip_serializing_if = "Option::is_none")]
    pub knowledge_base_queries: Option<Vec<models::KnowledgeBaseQueryDetail>>,
}

impl ListKnowledgeBaseQueriesResponseContent {
    pub fn new() -> ListKnowledgeBaseQueriesResponseContent {
        ListKnowledgeBaseQueriesResponseContent {
            knowledge_base_queries: None,
        }
    }
}

