/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListApiKeysResponseContent {
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<f64>,
    #[serde(rename = "api_keys")]
    pub api_keys: Vec<models::ApiKeyDetail>,
}

impl ListApiKeysResponseContent {
    pub fn new(api_keys: Vec<models::ApiKeyDetail>) -> ListApiKeysResponseContent {
        ListApiKeysResponseContent {
            page: None,
            api_keys,
        }
    }
}

