/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListRulesResponseContent {
    #[serde(rename = "rules")]
    pub rules: Vec<models::RuleDetail>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::Pagination>,
}

impl ListRulesResponseContent {
    pub fn new(rules: Vec<models::RuleDetail>, pagination: models::Pagination) -> ListRulesResponseContent {
        ListRulesResponseContent {
            rules,
            pagination: Box::new(pagination),
        }
    }
}

