/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListBucketsResponseContent {
    #[serde(rename = "buckets")]
    pub buckets: Vec<models::BucketDetail>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::Pagination>,
}

impl ListBucketsResponseContent {
    pub fn new(buckets: Vec<models::BucketDetail>, pagination: models::Pagination) -> ListBucketsResponseContent {
        ListBucketsResponseContent {
            buckets,
            pagination: Box::new(pagination),
        }
    }
}

