/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListEventsResponseContent {
    #[serde(rename = "events")]
    pub events: Vec<models::EventDetail>,
    #[serde(rename = "count")]
    pub count: f64,
    #[serde(rename = "total_count")]
    pub total_count: f64,
    #[serde(rename = "limit")]
    pub limit: f64,
    #[serde(rename = "offset")]
    pub offset: f64,
    #[serde(rename = "next_offset")]
    pub next_offset: f64,
}

impl ListEventsResponseContent {
    pub fn new(events: Vec<models::EventDetail>, count: f64, total_count: f64, limit: f64, offset: f64, next_offset: f64) -> ListEventsResponseContent {
        ListEventsResponseContent {
            events,
            count,
            total_count,
            limit,
            offset,
            next_offset,
        }
    }
}

