/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelTokenCounts {
    #[serde(rename = "input", skip_serializing_if = "Option::is_none")]
    pub input: Option<f32>,
    #[serde(rename = "output", skip_serializing_if = "Option::is_none")]
    pub output: Option<f32>,
}

impl ModelTokenCounts {
    pub fn new() -> ModelTokenCounts {
        ModelTokenCounts {
            input: None,
            output: None,
        }
    }
}

