/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pagination {
    #[serde(rename = "total_count")]
    pub total_count: f64,
    #[serde(rename = "page_number")]
    pub page_number: f64,
    #[serde(rename = "page_size")]
    pub page_size: f64,
    #[serde(rename = "total_pages")]
    pub total_pages: f64,
    #[serde(rename = "next_page", skip_serializing_if = "Option::is_none")]
    pub next_page: Option<f64>,
    #[serde(rename = "previous_page", skip_serializing_if = "Option::is_none")]
    pub previous_page: Option<f64>,
}

impl Pagination {
    pub fn new(total_count: f64, page_number: f64, page_size: f64, total_pages: f64) -> Pagination {
        Pagination {
            total_count,
            page_number,
            page_size,
            total_pages,
            next_page: None,
            previous_page: None,
        }
    }
}

