/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Period {
    #[serde(rename = "1m")]
    Variant1m,
    #[serde(rename = "1h")]
    Variant1h,
    #[serde(rename = "1d")]
    Variant1d,
    #[serde(rename = "1w")]
    Variant1w,

}

impl std::fmt::Display for Period {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant1m => write!(f, "1m"),
            Self::Variant1h => write!(f, "1h"),
            Self::Variant1d => write!(f, "1d"),
            Self::Variant1w => write!(f, "1w"),
        }
    }
}

impl Default for Period {
    fn default() -> Period {
        Self::Variant1m
    }
}

