/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunDurationGauge {
    #[serde(rename = "total_seconds", skip_serializing_if = "Option::is_none")]
    pub total_seconds: Option<f64>,
    #[serde(rename = "activity_durations", skip_serializing_if = "Option::is_none")]
    pub activity_durations: Option<Vec<models::ActivityDuration>>,
}

impl RunDurationGauge {
    pub fn new() -> RunDurationGauge {
        RunDurationGauge {
            total_seconds: None,
            activity_durations: None,
        }
    }
}

