/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunCountGauge {
    #[serde(rename = "active_count", skip_serializing_if = "Option::is_none")]
    pub active_count: Option<f64>,
    #[serde(rename = "total_count", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<f64>,
}

impl RunCountGauge {
    pub fn new() -> RunCountGauge {
        RunCountGauge {
            active_count: None,
            total_count: None,
        }
    }
}

