/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct S3 {
    #[serde(rename = "s3")]
    pub s3: Box<models::S3ConnectorInput>,
}

impl S3 {
    pub fn new(s3: models::S3ConnectorInput) -> S3 {
        S3 {
            s3: Box::new(s3),
        }
    }
}

