/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct S3ConnectorInput {
    #[serde(rename = "uris")]
    pub uris: Vec<String>,
    #[serde(rename = "aws_access_key_id")]
    pub aws_access_key_id: String,
    #[serde(rename = "aws_secret_access_key")]
    pub aws_secret_access_key: String,
}

impl S3ConnectorInput {
    pub fn new(uris: Vec<String>, aws_access_key_id: String, aws_secret_access_key: String) -> S3ConnectorInput {
        S3ConnectorInput {
            uris,
            aws_access_key_id,
            aws_secret_access_key,
        }
    }
}

