/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SlackDetail {
    #[serde(rename = "app_name")]
    pub app_name: String,
    #[serde(rename = "app_display_name")]
    pub app_display_name: String,
    #[serde(rename = "app_description")]
    pub app_description: String,
    #[serde(rename = "app_manifest", deserialize_with = "Option::deserialize")]
    pub app_manifest: Option<serde_json::Value>,
    #[serde(rename = "bot_token_secret_ref")]
    pub bot_token_secret_ref: String,
    #[serde(rename = "signing_secret_secret_ref")]
    pub signing_secret_secret_ref: String,
}

impl SlackDetail {
    pub fn new(app_name: String, app_display_name: String, app_description: String, app_manifest: Option<serde_json::Value>, bot_token_secret_ref: String, signing_secret_secret_ref: String) -> SlackDetail {
        SlackDetail {
            app_name,
            app_display_name,
            app_description,
            app_manifest,
            bot_token_secret_ref,
            signing_secret_secret_ref,
        }
    }
}

