/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Slack1 {
    #[serde(rename = "slack")]
    pub slack: Box<models::SlackDetail>,
}

impl Slack1 {
    pub fn new(slack: models::SlackDetail) -> Slack1 {
        Slack1 {
            slack: Box::new(slack),
        }
    }
}

