/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Structure1 {
    #[serde(rename = "structure")]
    pub structure: Box<models::StructureConnectorDetail>,
}

impl Structure1 {
    pub fn new(structure: models::StructureConnectorDetail) -> Structure1 {
        Structure1 {
            structure: Box::new(structure),
        }
    }
}

