/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StructureConnectorDetail {
    #[serde(rename = "structure_id")]
    pub structure_id: String,
    #[serde(rename = "args", skip_serializing_if = "Option::is_none")]
    pub args: Option<Vec<String>>,
}

impl StructureConnectorDetail {
    pub fn new(structure_id: String) -> StructureConnectorDetail {
        StructureConnectorDetail {
            structure_id,
            args: None,
        }
    }
}

