/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TempGoogleDriveInput {
    #[serde(rename = "access_token")]
    pub access_token: String,
    #[serde(rename = "refresh_token")]
    pub refresh_token: String,
    #[serde(rename = "file_ids")]
    pub file_ids: Vec<String>,
}

impl TempGoogleDriveInput {
    pub fn new(access_token: String, refresh_token: String, file_ids: Vec<String>) -> TempGoogleDriveInput {
        TempGoogleDriveInput {
            access_token,
            refresh_token,
            file_ids,
        }
    }
}

