/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransformDetail {
    #[serde(rename = "structure", skip_serializing_if = "Option::is_none")]
    pub structure: Option<Box<models::StructureConnectorDetail>>,
}

impl TransformDetail {
    pub fn new() -> TransformDetail {
        TransformDetail {
            structure: None,
        }
    }
}

