/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateApiKeyResponseContent {
    #[serde(rename = "api_key_id")]
    pub api_key_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "last_used")]
    pub last_used: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "active")]
    pub active: bool,
}

impl UpdateApiKeyResponseContent {
    pub fn new(api_key_id: String, name: String, created_at: String, last_used: String, updated_at: String, active: bool) -> UpdateApiKeyResponseContent {
        UpdateApiKeyResponseContent {
            api_key_id,
            name,
            created_at,
            last_used,
            updated_at,
            active,
        }
    }
}

