/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateKnowledgeBaseRequestContent {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "data_connector_ids", skip_serializing_if = "Option::is_none")]
    pub data_connector_ids: Option<Vec<String>>,
}

impl UpdateKnowledgeBaseRequestContent {
    pub fn new() -> UpdateKnowledgeBaseRequestContent {
        UpdateKnowledgeBaseRequestContent {
            name: None,
            description: None,
            data_connector_ids: None,
        }
    }
}

