/*
 * Griptape Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-09-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebscraperDetail {
    #[serde(rename = "urls")]
    pub urls: Vec<String>,
}

impl WebscraperDetail {
    pub fn new(urls: Vec<String>) -> WebscraperDetail {
        WebscraperDetail {
            urls,
        }
    }
}

